services:
  - type: web
    name: web-edukasi
    runtime: docker
    plan: free
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php spark cache:clear
    startCommand: >
      echo ">>> MIGRATE MULAI..." &&
      php spark migrate --all --no-interaction > /tmp/migrate.log 2>&1 ||
      echo ">>> MIGRATE GAGAL" &&
      cat /tmp/migrate.log &&
      echo ">>> APACHE START..." &&
      apache2-foreground
