services:
  - type: web
    name: web-edukasi
    runtime: docker
    plan: free
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php spark migrate --all --no-interaction
    startCommand: apache2-foreground
