services:
  - type: web
    name: web-edukasi
    runtime: docker
    plan: free
    region: singapore
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
