services:
  - type: web
    name: web-edukasi
    runtime: docker
    region: singapore
    plan: free
    buildCommand: "composer install --no-dev"
    startCommand: "php spark serve --host 0.0.0.0 --port $PORT"
    rootDir: .
