services:
  - type: web
    name: web-edukasi
    runtime: docker
    plan: free
    region: singapore
    buildCommand: docker build -t ci-app .
    startCommand: docker run -p 80:80 ci-app
    rootDir: .
